Implements callback & sign require Base64 document
monpetitplacement/mpp-universign-bundle pull request #5
Opened 2020-11-05 13:15 UTC by Gwemox

2020-11-05 13:47 UTC, konandrum requested changes

2020-11-05 13:47 UTC, konandrum commented on Requester/XmlRpcRequester.php
> +            !($data instanceof Base64)
Keep full FQCN

2020-11-05 13:47 UTC, konandrum commented on Requester/XmlRpcRequester.php
> +                ->setState(TransactionResponse::STATE_SUCCESS);
syntax

2020-11-05 13:47 UTC, konandrum commented on Requester/XmlRpcRequester.php
> +                ->setErrorMessage($fe->getMessage());
syntax

2020-11-05 13:47 UTC, konandrum commented on Requester/XmlRpcRequester.php
> +                ->setRedirectWait($response['redirectWait'] ?? null);
syntax

2020-11-05 13:47 UTC, konandrum commented on Requester/XmlRpcRequester.php
> +                ->setErrorMessage($fe->getMessage());
syntax

2020-11-05 13:47 UTC, konandrum commented on Requester/XmlRpcRequester.php
> +                ->setRedirectWait($response['redirectWait'] ?? null);
syntax

2020-11-05 13:47 UTC, konandrum commented on Requester/XmlRpcRequester.php
> +                ->setErrorMessage($fe->getMessage());
syntax

2020-11-05 13:47 UTC, konandrum commented on Requester/XmlRpcRequester.php
> +                ->setState(TransactionInfo::STATE_SUCCESS);
syntax

2020-11-05 13:47 UTC, konandrum commented on Requester/XmlRpcRequester.php
> +                ->setErrorMessage($fe->getMessage());
syntax

2020-11-05 13:47 UTC, konandrum commented on Requester/XmlRpcRequester.php
> +                ->setState(TransactionInfo::STATE_SUCCESS);
syntax

2020-11-05 13:47 UTC, konandrum commented on Requester/XmlRpcRequester.php
> +                ->setErrorMessage($fe->getMessage());
syntax

2020-11-05 15:52 UTC, Gwemox commented on Requester/XmlRpcRequester.php
> +                ->setErrorMessage($fe->getMessage());
Fix

2020-11-05 15:52 UTC, Gwemox commented on Requester/XmlRpcRequester.php
> +                ->setState(TransactionInfo::STATE_SUCCESS);
Fix

2020-11-05 15:52 UTC, Gwemox commented on Requester/XmlRpcRequester.php
> +                ->setErrorMessage($fe->getMessage());
Fix

2020-11-05 15:52 UTC, Gwemox commented on Requester/XmlRpcRequester.php
> +                ->setState(TransactionInfo::STATE_SUCCESS);
Fix

2020-11-05 15:52 UTC, Gwemox commented on Requester/XmlRpcRequester.php
> +                ->setErrorMessage($fe->getMessage());
Fix

2020-11-05 15:52 UTC, Gwemox commented on Requester/XmlRpcRequester.php
> +                ->setErrorMessage($fe->getMessage());
Fix

2020-11-05 15:52 UTC, Gwemox commented on Requester/XmlRpcRequester.php
> +                ->setRedirectWait($response['redirectWait'] ?? null);
Fix

2020-11-05 15:52 UTC, Gwemox commented on Requester/XmlRpcRequester.php
> +                ->setErrorMessage($fe->getMessage());
Fix

2020-11-05 15:52 UTC, Gwemox commented on Requester/XmlRpcRequester.php
> +                ->setState(TransactionResponse::STATE_SUCCESS);
Fix

2020-11-05 15:52 UTC, Gwemox commented on Requester/XmlRpcRequester.php
> +            !($data instanceof Base64)
Fix

2020-11-06 14:02 UTC, konandrum requested changes

2020-11-06 14:02 UTC, konandrum commented on Event/UniversignCallbackEvent.php
> +     * All signatories have signed BUT awaiting validation by the Universign registration authority. All signatories have signed.
```suggestion
     * All signatories have signed BUT waiting for Universign registration authority validation.
```

2020-11-06 14:03 UTC, merged